services:
  hivebox:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8000:8000"

  redis:
    image: redis:7.4.3-alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --loglevel
      - debug
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # minio:
  #   image: minio/minio:RELEASE.2025-06-13T11-33-47Z-cpuv1
  #   environment:
  #     MINIO_ROOT_USER:  ${MINIO_ROOT_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #   volumes:
  #     - ./data:/data
  #   command: ["server", "/data"]
  #   restart: unless-stopped

volumes:
  redis_data: