services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
      - minio
    ports:
      - "8000:8000"

  redis:
    image: redis:7.4.3-alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - no
      - --loglevel
      - debug
    tmpfs:
      - /data

  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    environment:
      MINIO_ROOT_USER:  ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data
    command: ["server", "/data"]
    restart: unless-stopped