services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8000:8000"

  redis:
    image: redis:7.4.3-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--loglevel", "debug"]