name: ClusterFuzzLite PR fuzzing
on:
  pull_request:
    paths:
      - '**/*.py'
  workflow_dispatch:
     
permissions: read-all
jobs:
  Fuzzing:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@40f9a53e632516d2ec9f738eadd284635529fbad
        with:
          language: python
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: ${{ matrix.sanitizer }}

      - name: Run Fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@40f9a53e632516d2ec9f738eadd284635529fbad
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 60
          mode: 'code-change'
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
