name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 

      - name: Setup Python
        uses: actions/setup-python@b8cf3eb1ebc9c7f906e4ca96fcdf2e289e25d230 
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'

      - name: Install dependencies
        run: pip install --require-hashes -r requirements-dev.txt
          
      - name: Lint Python code
        run: pylint --fail-under=8 src/

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@d292784f8f3eacda47060b259a580467b0ba410c 
        with:
          dockerfile: Dockerfile

      - name: Run unit tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd)/src pytest src/tests

      - name: Build Docker image
        run: docker build -t hivebox:test .

      - name: Test version endpoint
        run: |
          pip install .
          docker run -d -p 8000:8000 --name hivebox-test hivebox:test
          sleep 5
          EXPECTED_VERSION=$(python -c "from hivebox import __version__; print(__version__)")
          VERSION=$(curl -s http://localhost:8000/version | python -c "import sys, json; print(json.load(sys.stdin)['hivebox'])")
          if [ "$VERSION" != "$EXPECTED_VERSION" ]; then
            echo "Version mismatch: API returned $VERSION but package version is $EXPECTED_VERSION"
            exit 1
          fi
